// react_study/0_学习/05_src_github搜索案例_pubsub/component/Search/index.jsx
import React, { Component } from 'react'
import axios from 'axios'
import PubSub from 'pubsub-js'
export default class Search extends Component {
  state = { keyword: '' }
  // 存储关键词
  keyWord = e => {
    this.setState({ keyword: e.target.value })
  }
  // 发送请求获取数据
  getSearchData = async () => {
    const { keyword } = this.state
    let res = await axios.get(`http://localhost:3000/api/search/users?q=${keyword}`)
    PubSub.publish('data', res.data.items)
  }
  render() {
    return (
      <section className='jumbotron'>
        <h3 className='jumbotron-heading'>Search Github Users</h3>
        <div>
          <input
            type='text'
            placeholder='enter the name you search'
            onKeyUp={this.keyWord}
          />
          &nbsp;<button onClick={this.getSearchData}>Search</button>
        </div>
      </section>
    )
  }
}

// Vue2学习/vue_test/1.笔记/11.github搜索功能/components/Search.vue
<template>
  <section class="jumbotron">
    <h3 class="jumbotron-heading">Search Github Users</h3>
    <div>
      <input
        type="text"
        v-model="keyWord"
        placeholder="enter the name you search"
      />&nbsp;
      <button @click="getList">Search</button>
    </div>
  </section>
</template>

<script>
import axios from 'axios'
export default {
  name: 'Search',
  data() {
    return {
      keyWord: '',
    }
  },
  methods: {
    getList() {
      this.$bus.$emit('getInfoData', {
        users: [],
        isFirst: false,
        isLoading: true,
        errMsg: '',
      })
      //发送请求
      axios.get(`https://api.github.com/search/users?q=${this.keyWord}`).then(
        (response) => {
          this.$bus.$emit('getInfoData', {
            users: response.data.items,
            isLoading: false,
            errMsg: '',
          })
        },
        (error) => {
          //错误信息
          this.$bus.$emit('getInfoData', {
            users: [],
            isLoading: false,
            errMsg: error.message,
          })
        }
      )
    },
  },
}
</script>

<style scoped>
</style>
