// Vue2学习/vue_test/src/pages/Message.vue
<template>
  <div>
    <!-- 注意：想要使用params传参数就要在路由文件中给配置项写name还有相对应的占位参数 -->
    <ul>
      <li v-for="m in message" :key="m.id">
        <!-- 第一种形式 -->
        <!-- <router-link :to="`/home/message/detail/${m.id}/${m.title}`">
          {{ m.title }}
        </router-link>&nbsp;&nbsp; -->

        <!-- 要是想要用params 这个配置项，就只能以对象的形式来写 （对象形式）-->
        <router-link :to="{
            path: '/home/message/detail/',
            query:
            {
              id: m.id,
              title: m.title
            }
          }">
          {{ m.title }}
        </router-link>&nbsp;&nbsp;
        <button @click="pushShow(m)">push查看</button>
        <button @click="replaceShow(m)">replace查看</button>
      </li>
    </ul>
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: 'message',
  data() {
    return {
      message: [
        {
          id: '001',
          title: '消息001'
        },
        {
          id: '002',
          title: '消息002'
        },
        {
          id: '003',
          title: '消息003'
        },
      ]
    }
  },
  methods: {
    pushShow(m) {
      // console.log(this.$router);
      this.$router.push({
        name: 'detail',
        query:
        {
          id: m.id,
          title: m.title
        }
      })
    },
    replaceShow(m) {
      this.$router.replace({
        name: 'detail',
        query:
        {
          id: m.id,
          title: m.title
        }
      })
    },
  },
}
</script>

<style></style>

// react_study/0_学习/10_src_withRouter的使用/pages/Home/Message/index.jsx
import React, { Component } from 'react'
import Detail from '../Detail'
import { Link, Route } from 'react-router-dom'

export default class Message extends Component {
  state = {
    message: [
      { id: '1', title: '消息1' },
      { id: '2', title: '消息2' },
      { id: '3', title: '消息3' },
    ],
  }
  /* 编程式路由导航 */
  // push跳转 params参数
  showPush = (id, title) => {
    this.props.history.push(`/home/message/detail/${id}/${title}`)
  }
  // replace跳转 params参数
  showRepalce = (id, title) => {
    this.props.history.replace(`/home/message/detail/${id}/${title}`)
  }

  render() {
    const { message } = this.state
    return (
      <div>
        <ul>
          {/* state参数 */}
          {message.map(item => {
            return (
              <li key={item.id}>
                <Link to={`/home/message/detail/${item.id}/${item.title}`}>
                  {item.title}
                </Link>
                &nbsp;&nbsp;
                <button onClick={() => this.showPush(item.id, item.title)}>
                  push查看
                </button>
                &nbsp;&nbsp;
                <button onClick={() => this.showRepalce(item.id, item.title)}>
                  replace查看
                </button>
                &nbsp;&nbsp;
              </li>
            )
          })}
        </ul>
        <hr />
        <Route path='/home/message/detail/:id/:title' component={Detail}></Route>
      </div>
    )
  }
}
