// react_study/0_学习/06_src_NavLink和Link以及封装NavLink/App.js
import React, { Component } from 'react'
import Header from './components/Header'
// 引入路由库
import { Route } from 'react-router-dom'
import Home from './pages/Home'
import About from './pages/About'
import MyNavLink from './components/MyNavLink'

export default class App extends Component {
  render() {
    return (
      <div>
        <Header />
        <div className='row'>
          <div className='col-xs-2 col-xs-offset-2'>
            <div className='list-group'>
              {/* 
                默认路由链接Link，但是不能切换选中颜色              
              */}
              {/* <Link activeClassName='active' className='list-group-item' to='/about'>
                About
              </Link>
              <Link activeClassName='active' className='list-group-item' to='/home'>
                Home
              </Link> */}

              {/*
              NavLin中activeClassName默认是active
                react路由链接
                activeClassName是被选中的样式
              */}
              {/* 
              <NavLink activeClassName='active' className='list-group-item' to='/about'>
                About
              </NavLink>
              <NavLink activeClassName='active' className='list-group-item' to='/home'>
                Home
              </NavLink> 
              */}
              {/* 
                自己封装的NavLink 
                可以通过this.props.children来接受标签体内容，类似vue的slot
                也是控制显示标签体内容
              */}
              <MyNavLink to='/about'>About</MyNavLink>
              <MyNavLink to='/home'>Home</MyNavLink>
            </div>
          </div>
          <div className='col-xs-6'>
            <div className='panel'>
              <div className='panel-body'>
                <Route path='/home' component={Home} />
                <Route path='/about' component={About} />
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }
}

// Vue2学习/vue_test/1.笔记/18.路由的props传参数/App.vue
<template>
  <div>
    <div class="row">
      <div class="col-xs-offset-2 col-xs-8">
        <div class="page-header">
          <h2>Vue Router Demo</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-2 col-xs-offset-2">
        <div class="list-group">
          <!-- 通过a标签来实现页面的跳转 -->
          <!-- <a class="list-group-item active" href="./about.html">About</a>
          <a class="list-group-item" href="./home.html">Home</a> -->

          <!-- 路由是通过 router-link 来进行页面的局部刷新-->
          <!-- 路由是通过 router-link 来进行页面的局部刷新-->
          <!-- 路由是通过 router-link 中的 active-class 来实现页面选中的css效果-->
          <router-link class="list-group-item" active-class="active" to="/about">
            About
          </router-link>
          <router-link class="list-group-item" active-class="active" to="/home">
            Home
          </router-link>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="panel">
          <div class="panel-body">
            <!-- 路由是通过 router-view 来实现对应组件显示-->
            <router-view>
            </router-view>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>

export default {
  name: 'App',
}
</script>
<style></style>
