// Vue2学习/vue_test/1.笔记/18.路由的props传参数/pages/Message.vue
<template>
  <div>
    <!-- 注意：想要使用params传参数就要在路由文件中给配置项写name还有相对应的占位参数 -->
    <ul>
      <li v-for="m in message" :key="m.id">
        <!-- 第一种形式 -->
        <!-- <router-link :to="`/home/message/detail/${m.id}/${m.title}`">
          {{ m.title }}
        </router-link>&nbsp;&nbsp; -->

        <!-- 要是想要用params 这个配置项，就只能以对象的形式来写 （对象形式）-->
        <router-link :to="{
            name: 'detail',
            query:
            {
              id: m.id,
              title: m.title
            }
          }">
          {{ m.title }}
        </router-link>&nbsp;&nbsp;
      </li>
    </ul>
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: 'message',
  data() {
    return {
      message: [
        {
          id: '001',
          title: '消息001'
        },
        {
          id: '002',
          title: '消息002'
        },
        {
          id: '003',
          title: '消息003'
        },
      ]
    }
  },
  mounted() {
    console.log(this);
  },
}
</script>

<style></style>

// react_study/0_学习/08_src_传递search(query)参数/pages/Home/Message/index.jsx
import React, { Component } from 'react'
import Detail from '../Detail'
import { Link, Route } from 'react-router-dom'

export default class Message extends Component {
  state = {
    message: [
      { id: 1, title: '消息1' },
      { id: 2, title: '消息2' },
      { id: 3, title: '消息3' },
    ],
  }
  render() {
    const { message } = this.state
    return (
      <div>
        <ul>
          {/* search参数 相当于query传参 */}
          {message.map(item => {
            return (
              <li key={item.id}>
                <Link to={`/home/message/detail?id=${item.id}&title=${item.title}`}>
                  {item.title}
                </Link>
                &nbsp;&nbsp;
              </li>
            )
          })}
        </ul>
        <hr />
        {/* search参数无须接受 */}
        <Route path='/home/message/detail' component={Detail}></Route>
      </div>
    )
  }
}
