// Vue2学习/vue_test/src/App.vue
<template>
  <div>
    <div class="row">
      <div class="col-xs-offset-2 col-xs-8">
        <Banner></Banner>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-2 col-xs-offset-2">
        <div class="list-group">
          <!-- 通过a标签来实现页面的跳转 -->
          <!-- <a class="list-group-item active" href="./about.html">About</a>
          <a class="list-group-item" href="./home.html">Home</a> -->

          <!-- 路由是通过 router-link 来进行页面的局部刷新-->
          <!-- 路由是通过 router-link 来进行页面的局部刷新-->
          <!-- 路由是通过 router-link 中的 active-class 来实现页面选中的css效果-->
          <router-link class="list-group-item" active-class="active" to="/about">
            About
          </router-link>
          <router-link class="list-group-item" active-class="active" to="/home">
            Home
          </router-link>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="panel">
          <div class="panel-body">
            <!-- 路由是通过 router-view 来实现对应组件显示-->
            <router-view>
            </router-view>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Banner from './components/Banner.vue';
export default {
  name: 'App',
  components: {
    Banner
  }
}
</script>
<style></style>

// react_study/0_学习/09_src_编程式路由导航/App.js
import React, { Component } from 'react'
import Header from './components/Header'
// 引入路由库
import { Route, Switch, Redirect } from 'react-router-dom'
import Home from './pages/Home'
import About from './pages/About'
import MyNavLink from './components/MyNavLink'

export default class App extends Component {
  render() {
    return (
      <div>
        <Header />
        <div className='row'>
          <div className='col-xs-2 col-xs-offset-2'>
            <div className='list-group'>
              {/* 
                默认路由链接Link，但是不能切换选中颜色              
              */}
              {/* <Link activeClassName='active' className='list-group-item' to='/about'>
                About
              </Link>
              <Link activeClassName='active' className='list-group-item' to='/home'>
                Home
              </Link> */}

              {/*
              NavLin中activeClassName默认是active
                react路由链接
                activeClassName是被选中的样式
              */}
              {/* 
              <NavLink activeClassName='active' className='list-group-item' to='/about'>
                About
              </NavLink>
              <NavLink activeClassName='active' className='list-group-item' to='/home'>
                Home
              </NavLink> 
              */}
              {/* 
                自己封装的NavLink 
                可以通过this.props.children来接受标签体内容，类似vue的slot
                也是控制显示标签体内容
              */}
              <MyNavLink to='/about'>About</MyNavLink>
              <MyNavLink to='/home'>Home</MyNavLink>
            </div>
          </div>
          <div className='col-xs-6'>
            <div className='panel'>
              <div className='panel-body'>
                {/* 注册路由 
                  Swich是解决一个路径出现两个组件
                  Swich就是匹配上了一个就不会出现下一个
                  exact是严格匹配
                */}
                <Switch>
                  {/* Redirect是重定向 */}
                  <Route path='/home' component={Home} />
                  <Route path='/about' component={About} />
                  <Redirect path='/home' />
                </Switch>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }
}
